controller_manager:
  ros__parameters:
    update_rate: 250

joint_state_broadcaster:
  ros__parameters: {}

# Use the UR driver's controller name so MoveIt config matches both real/fake
scaled_joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces: [position]
    state_interfaces: [position, velocity]
