chess_arm_executor:
  ros__parameters:
    planning_group: "ur_manipulator"
    ee_link: "tool0"
    planner_id: "RRTConnectkConfigDefault"
    velocity_scaling: 0.5
    accel_scaling: 0.5

    board_frame: "board"
    world_frame: "world"
    square_size: 0.040
    z_approach: 0.070
    home_named_target: "home"

    # piece-specific descend heights (to the grasp height)
    z_pick_pawn:   0.018
    z_pick_knight: 0.022
    z_pick_bishop: 0.022
    z_pick_rook:   0.025
    z_pick_queen:  0.028
    z_pick_king:   0.030
